name: build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run unit tests
        run: ./gradlew clean build optimizedJar --parallel

  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Start local Blockchain
        run: docker logout public.ecr.aws && docker-compose up -d

      - name: Check if all contracts are deployable
        run: ./gradlew deployContractsToLocal --parallel --max-workers=2

      - name: Run integration tests
        run: ./gradlew integrationTest --parallel --max-workers=2