name: push-main

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: install docker & docker-compose
        run: apt install docker docker-compose

      - name: run docker-compose
        run: docker-compose up -d

      - name: Build optimized jar
        run: ./gradlew clean build optimizedJar integrationTest
#test