name: push-main

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Start local Blockchain
        run: docker-compose up -d

      - name: Run unit tests
        run: ./gradlew clean build

      - name: Optimize Jar
        run: ./gradlew optimizedJar

      - name: Run integration tests
        run: ./gradlew integrationTest