name: push-main

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: install docker & docker-compose
        run: sudo curl -sSL https://get.docker.com/ | sh && sudo apt install docker-compose -y 

      - name: start docker
        run: sudo systemctl start docker

      - name: run docker-compose
        run: sudo docker-compose up -d

      - name: Build optimized jar
        run: ./gradlew clean build optimizedJar integrationTest
#test